name: Test CSharp

on:
  push:
    paths:
      - 'CSharp/**'
      - '.github/workflows/CSharp.yml'
  pull_request:
    paths:
      - 'CSharp/**'
      - '.github/workflows/CSharp.yml'

jobs:
  build:
    runs-on: windows-latest

    env:
      DB_USER: root
      DB_OLD_PASSWORD:
      DB_PASSWORD: mysql

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Start MYSQL
      uses: shogo82148/actions-setup-mysql@v1.23.0
      with:
        mysql-version: "8.0"

    - name: Configure MYSQL and import DB
      run: |
        mysqladmin --user=${{ env.DB_USER }} --password=${{ env.DB_OLD_PASSWORD }} password ${{ env.DB_PASSWORD }}
        mysql --version
        type .\build\Database\initDatabase.sql | mysql -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
#       mysql -ustore -p123456 myShop -e "insert into myShop.RECEIPT (AMOUNT, TAX, TOTAL) values(1, 2, 3);"

    - name: Cache Nuget packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: ${{ runner.os }}-nuget

    - name: Build and test
      working-directory: CSharp
      run: |
        dotnet restore
        dotnet build
        dotnet test -v n --filter "Test1|Test2|Test3|Test4"
