name: Test CSharp

on:
  push:
    paths:
      - 'CSharp/**'
      - '.github/workflows/CSharp.yml'
  pull_request:
    paths:
      - 'CSharp/**'
      - '.github/workflows/CSharp.yml'

jobs:
  build:
    runs-on: windows-latest

    env:
      DB_USER: root
      DB_OLD_PASSWORD: root
      DB_PASSWORD: mysql

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Start MYSQL and import DB
      run: |
        mysqld --initialize-insecure --console
        start "MySQL" "mysqld --standalone"
        timeout /t 5
        mysqladmin --user=${{ env.DB_USER }} --password=${{ env.DB_OLD_PASSWORD }} password ${{ env.DB_PASSWORD }}
        mysql --version
        echo ${GITHUB_WORKSPACE}/build/Database/initDatabase.sql | mysql -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}

    - name: Set up CSharp
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 4.7.2
    - name: use nuget cache
      uses: actions/cache@v2
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: ${{ runner.os }}-nuget

    - name: install dependencies
      working-directory: CSharp
      run: dotnet restore

    - name: build solution
      working-directory: CSharp
      run: dotnet build

    - name: run unit tests
      working-directory: CSharp
      run: dotnet test"

    - name: Stop MYSQL
      run: mysqladmin mysql -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }} shutdown
